In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report,confusion_matrix


In [3]:
df=pd.read_csv('IRIS.csv')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   species       150 non-null    object 
dtypes: float64(4), object(1)
memory usage: 6.0+ KB


In [4]:
X=df.drop('species',axis=1)
y=df.species
scaler=MinMaxScaler()
X=scaler.fit_transform(X)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 45)


In [5]:
from sklearn.svm import SVC
print('Support Vector Classification with linear kernel')

model = SVC(kernel='linear')
model.fit(X_train, y_train)
y_pred=model.predict(X_test)

cm = confusion_matrix(y_test, y_pred)
print ("Confusion Matrix : \n", cm)
print ('Classification Report : ')
print (classification_report(y_test, y_pred))

Support Vector Classification with linear kernel
Confusion Matrix : 
 [[11  0  0]
 [ 0  7  0]
 [ 0  1 11]]
Classification Report : 
                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        11
Iris-versicolor       0.88      1.00      0.93         7
 Iris-virginica       1.00      0.92      0.96        12

       accuracy                           0.97        30
      macro avg       0.96      0.97      0.96        30
   weighted avg       0.97      0.97      0.97        30



In [6]:
from sklearn.svm import SVC
print('Support Vector Classification with rbf kernel')

model = SVC(kernel='rbf')
model.fit(X_train, y_train)
y_pred=model.predict(X_test)

cm = confusion_matrix(y_test, y_pred)
print ("Confusion Matrix : \n", cm)
print ('Classification Report : ')
print (classification_report(y_test, y_pred))

Support Vector Classification with rbf kernel
Confusion Matrix : 
 [[11  0  0]
 [ 0  7  0]
 [ 0  1 11]]
Classification Report : 
                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        11
Iris-versicolor       0.88      1.00      0.93         7
 Iris-virginica       1.00      0.92      0.96        12

       accuracy                           0.97        30
      macro avg       0.96      0.97      0.96        30
   weighted avg       0.97      0.97      0.97        30



In [7]:
from sklearn.svm import SVC
print('Support Vector Classification with polynomial kernel')

model = SVC(kernel='poly')
model.fit(X_train, y_train)
y_pred=model.predict(X_test)

cm = confusion_matrix(y_test, y_pred)
print ("Confusion Matrix : \n", cm)
print ('Classification Report : ')
print (classification_report(y_test, y_pred))

Support Vector Classification with polynomial kernel
Confusion Matrix : 
 [[11  0  0]
 [ 0  7  0]
 [ 0  2 10]]
Classification Report : 
                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        11
Iris-versicolor       0.78      1.00      0.88         7
 Iris-virginica       1.00      0.83      0.91        12

       accuracy                           0.93        30
      macro avg       0.93      0.94      0.93        30
   weighted avg       0.95      0.93      0.93        30



In [8]:
from sklearn.svm import SVC
print('Support Vector Classification with sigmoid kernel')

model = SVC(kernel='sigmoid')
model.fit(X_train, y_train)
y_pred=model.predict(X_test)

cm = confusion_matrix(y_test, y_pred)
print ("Confusion Matrix : \n", cm)
print ('Classification Report : ')
print (classification_report(y_test, y_pred))

Support Vector Classification with sigmoid kernel
Confusion Matrix : 
 [[6 0 5]
 [2 5 0]
 [8 4 0]]
Classification Report : 
                 precision    recall  f1-score   support

    Iris-setosa       0.38      0.55      0.44        11
Iris-versicolor       0.56      0.71      0.63         7
 Iris-virginica       0.00      0.00      0.00        12

       accuracy                           0.37        30
      macro avg       0.31      0.42      0.36        30
   weighted avg       0.27      0.37      0.31        30



In [9]:
from sklearn.linear_model import LogisticRegression
print('Logistic Regression')

model = LogisticRegression()
model.fit(X_train, y_train)
y_pred=model.predict(X_test)

cm = confusion_matrix(y_test, y_pred)
print ("Confusion Matrix : \n", cm)
print ('Classification Report : ')
print (classification_report(y_test, y_pred))

Logistic Regression
Confusion Matrix : 
 [[11  0  0]
 [ 0  6  1]
 [ 0  1 11]]
Classification Report : 
                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        11
Iris-versicolor       0.86      0.86      0.86         7
 Iris-virginica       0.92      0.92      0.92        12

       accuracy                           0.93        30
      macro avg       0.92      0.92      0.92        30
   weighted avg       0.93      0.93      0.93        30



In [10]:
from sklearn.neighbors import KNeighborsClassifier
print('K nearest neighbours classification')

model = KNeighborsClassifier()
model.fit(X_train, y_train)
y_pred=model.predict(X_test)

cm = confusion_matrix(y_test, y_pred)
print ("Confusion Matrix : \n", cm)
print ('Classification Report : ')
print (classification_report(y_test, y_pred))

K nearest neighbours classification
Confusion Matrix : 
 [[11  0  0]
 [ 0  7  0]
 [ 0  1 11]]
Classification Report : 
                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        11
Iris-versicolor       0.88      1.00      0.93         7
 Iris-virginica       1.00      0.92      0.96        12

       accuracy                           0.97        30
      macro avg       0.96      0.97      0.96        30
   weighted avg       0.97      0.97      0.97        30



In [11]:
from sklearn.tree import DecisionTreeClassifier
print('Decision Tree Classification')

model = DecisionTreeClassifier()
model.fit(X_train, y_train)
y_pred=model.predict(X_test)

cm = confusion_matrix(y_test, y_pred)
print ("Confusion Matrix : \n", cm)
print ('Classification Report : ')
print (classification_report(y_test, y_pred))

Decision Tree Classification
Confusion Matrix : 
 [[11  0  0]
 [ 0  7  0]
 [ 0  1 11]]
Classification Report : 
                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        11
Iris-versicolor       0.88      1.00      0.93         7
 Iris-virginica       1.00      0.92      0.96        12

       accuracy                           0.97        30
      macro avg       0.96      0.97      0.96        30
   weighted avg       0.97      0.97      0.97        30



In [12]:
from sklearn.ensemble import RandomForestClassifier
print('Random Forest Classification')

model = RandomForestClassifier()
model.fit(X_train, y_train)
y_pred=model.predict(X_test)

cm = confusion_matrix(y_test, y_pred)
print ("Confusion Matrix : \n", cm)
print ('Classification Report : ')
print (classification_report(y_test, y_pred))

Random Forest Classification
Confusion Matrix : 
 [[11  0  0]
 [ 0  7  0]
 [ 0  1 11]]
Classification Report : 
                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        11
Iris-versicolor       0.88      1.00      0.93         7
 Iris-virginica       1.00      0.92      0.96        12

       accuracy                           0.97        30
      macro avg       0.96      0.97      0.96        30
   weighted avg       0.97      0.97      0.97        30



In [13]:
from sklearn.ensemble import AdaBoostClassifier
print('Adaptive Boost Classification')

model = AdaBoostClassifier()
model.fit(X_train, y_train)

model.fit(X_train, y_train)
y_pred=model.predict(X_test)

cm = confusion_matrix(y_test, y_pred)
print ("Confusion Matrix : \n", cm)
print ('Classification Report : ')
print (classification_report(y_test, y_pred))

Adaptive Boost Classification
Confusion Matrix : 
 [[11  0  0]
 [ 0  7  0]
 [ 0  2 10]]
Classification Report : 
                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        11
Iris-versicolor       0.78      1.00      0.88         7
 Iris-virginica       1.00      0.83      0.91        12

       accuracy                           0.93        30
      macro avg       0.93      0.94      0.93        30
   weighted avg       0.95      0.93      0.93        30



In [14]:
from sklearn.ensemble import BaggingClassifier
print('Bagging Classification')

model = BaggingClassifier()
model.fit(X_train, y_train)

model.fit(X_train, y_train)
y_pred=model.predict(X_test)

cm = confusion_matrix(y_test, y_pred)
print ("Confusion Matrix : \n", cm)
print ('Classification Report : ')
print (classification_report(y_test, y_pred))

Bagging Classification
Confusion Matrix : 
 [[11  0  0]
 [ 0  7  0]
 [ 0  2 10]]
Classification Report : 
                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        11
Iris-versicolor       0.78      1.00      0.88         7
 Iris-virginica       1.00      0.83      0.91        12

       accuracy                           0.93        30
      macro avg       0.93      0.94      0.93        30
   weighted avg       0.95      0.93      0.93        30



In [15]:
from sklearn.ensemble import ExtraTreesClassifier
print('Extra trees Classification')

model = ExtraTreesClassifier()
model.fit(X_train, y_train)

model.fit(X_train, y_train)
y_pred=model.predict(X_test)

cm = confusion_matrix(y_test, y_pred)
print ("Confusion Matrix : \n", cm)
print ('Classification Report : ')
print (classification_report(y_test, y_pred))

Extra trees Classification


Confusion Matrix : 
 [[11  0  0]
 [ 0  7  0]
 [ 0  1 11]]
Classification Report : 
                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        11
Iris-versicolor       0.88      1.00      0.93         7
 Iris-virginica       1.00      0.92      0.96        12

       accuracy                           0.97        30
      macro avg       0.96      0.97      0.96        30
   weighted avg       0.97      0.97      0.97        30



In [16]:
from sklearn.neural_network import MLPClassifier
print('Multi Layer Perceptron Classification')

model = MLPClassifier()
model.fit(X_train, y_train)

model.fit(X_train, y_train)
y_pred=model.predict(X_test)

cm = confusion_matrix(y_test, y_pred)
print ("Confusion Matrix : \n", cm)
print ('Classification Report : ')
print (classification_report(y_test, y_pred))

Multi Layer Perceptron Classification


c:\Python312\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


Confusion Matrix : 
 [[11  0  0]
 [ 0  7  0]
 [ 0  0 12]]
Classification Report : 
                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        11
Iris-versicolor       1.00      1.00      1.00         7
 Iris-virginica       1.00      1.00      1.00        12

       accuracy                           1.00        30
      macro avg       1.00      1.00      1.00        30
   weighted avg       1.00      1.00      1.00        30



c:\Python312\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
